### ISSUE TITLE
R in JS

### ISSUE THREAD

**Issue by GarrisonD** [duncantl/RLLVMCompile#3]
Hello, @duncantl!

I am trying to run R functions in JS (frontend). I can achieve it by compiling LLVM IR to WASM module that can be easily loaded to browser and executed by `WebAssembly`.

With `RLLVMCompile` tool I can create wrappers for R functions and obtain its LLVM IR code.

Am I correct?

**Comment by duncantl** [comment]
Hi Garrison

Yes, you can use RLLVMCompile (or the new R2llvm that is newly migrating the RLLVMCompile to use some type inference information and an additional different  representation of R code) to generate the IR and then write that out to JS. 
This works for R code that doesn't rely on any operations that are built-in to the R interpreter,
i.e. at the C level.
